sudo: required

language: generic

services: 
  - docker

before_install:
  - docker build -t shlomisderot/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shlomisderot/docker-react npm run test